### ISSUE TITLE
Create a "News"section on the homepage

### ISSUE THREAD

**Issue by ThabangMash** [EclipseFdn/tangle.ee#7] opened 2020-05-07 17:41 UTC
Create a section of the home page that presents Tangle EE news, updates, events, and community announcements.

**Comment by autumnfound** [comment] 2020-05-07 18:11
We're in the progress of updating how news, events, and announcements are maintained and printed on the page. Instead of being maintained in Hugo, news and events are being maintained on newsroom.eclipse.org. We've added an enhancement to our jquery plugin to enable this to be more easily fetched. 

For an example of how this is implemented, we've recently finished our first Hugo migration for ECD Tools. The changes made to support this can be seen in the following 2 commits: https://github.com/EclipseFdn/ecdtools.eclipse.org/commit/2a5f6db7e11487f183f544c53a37bdddbd96cf39 https://github.com/EclipseFdn/ecdtools.eclipse.org/commit/958b5ed5989302bd84a36adfaedb452b46720ea1. The code for this plugin can be seen in the https://github.com/EclipseFdn/jquery-eclipsefdn-api repository. If the team supporting this site need any help, I'd be willing to support this enhancement!

@chrisguindon do we have a FeedBurner URL for Tangle yet, if not do we want one?

**Comment by chrisguindon** [comment] 2020-05-07 18:22
@autumnfound I added support for Tangle EE in Eclipse Newsroom:
https://newsroom.eclipse.org/node/add/news

**RSS**
https://newsroom.eclipse.org/rss/news/tangle_ee/news.xml

**API**
https://newsroom.eclipse.org/api/news?parameters[publish_to]=tangle_ee
https://newsroom.eclipse.org/api/events?parameters[publish_to]=tangle_ee

**Comment by chrisguindon** [comment] 2020-05-07 18:23
As mentioned by @autumnfound, please let us know how we can help!

**Comment by begonaalvarezd** [comment] 2020-06-15 10:54
Sorry for the delay, we have been very busy with other projects. We are finally discussing about this development and will try to implement it as soon as possible. Will get back to you if we have any question.

**Comment by begonaalvarezd** [comment] 2020-06-23 16:31
Hello @chrisguindon, we previously designed a component that could be used for this purpose but I have couple of questions before proceeding with the development?

- If we will show only the latest news, and add a CTA to your url to see all news https://newsroom.eclipse.org/, can that url get filtered to show only what is relevant to Tangle EE?
- Same as above but for events, https://events.eclipse.org/ can this url get filtered so it shows only relevant events?
- Is it though for the events to include a promotional image though the api? 
- Is there a strategy to promote upcoming events? 
- How much volume of new events do we expect having? 1event/month, 1/6months? 
 
Thank you very much! :)

**Comment by autumnfound** [comment] 2020-06-23 18:01
1. Yes, you can, for both events and news! There is a data attribute that you can set in the HTML of the element that will be detected by the plugin. I believe the attribute was called `data-publish-target` and needs to be set to a specific value set in newsroom, for this site its `tangle_ee`.
2. See above, same solution!
3. There are no images currently associated with events in the API, and I'm unaware of any plan to include such in at least the near future.
4. For the events HTML element, you should be able to set `data-upcoming="1"` to retrieve only upcoming events. In terms of promotion, we currently use the Featured Story/Footer components that appear at the top and bottom of a majority of our sites to promote upcoming events that we want to highlight.  
If you wish to promote events on say the IoT site, that would be more of a conversation to have with the marketing folks as they tend to have a more rigid schedule around when certain stories get highlighted.

I mentioned our plugin a lot but its not required to use it. It's just a more easily accessible way to asynchronously call the data. If you wish to implement your own solution that consumes raw JSON data, you can make calls to the API directly. You can see how we [make use of it in the plugin](https://github.com/EclipseFdn/jquery-eclipsefdn-api/blob/master/src/jquery.eclipsefdn-api.js#L1756) for URL query parameters. You can also use a web inspector on the traffic of some of our other sites that have implemented it for a more direct example (such as the eclipse.org or openhwgroup.org).

**Comment by begonaalvarezd** [comment] 2020-06-24 11:28
@autumnfound thank you very much for your fast reply! 
I dont really understand what you mean by:

> There is a data attribute that you can set in the HTML of the element that will be detected by the plugin.

My question was how to filter the website itself, not the feed which Christian already explained above. Since we are thinking of showing just 2-3 last news (using your api), we would like to offer the possibility to see the entire list that you host, for example adding a CTA that says "See all news" linking to the site https://newsroom.eclipse.org/. The problem is that that page shows all news, so I was wondering if that specific site could be filtered like https://newsroom.eclipse.org/?data-publish-target=tangle_ee or https://newsroom.eclipse.org/?parameters[data-publish-target]=tangle_ee (these are not working) to display only tangle_ee relevant news (same for events). 

Thanks! :)

**Comment by chrisguindon** [comment] 2020-06-24 12:43
@begonaalvarezd I hope all is well with you!

If you wish to link to the Eclipse Newsroom website, you can use the following URLs:

- https://newsroom.eclipse.org/audience/tangle_ee/news
- https://newsroom.eclipse.org/audience/tangle_ee/community-news
- https://newsroom.eclipse.org/audience/tangle_ee/announcements
- https://newsroom.eclipse.org/audience/tangle_ee/press-releases

You can also embed the news archive on your site if you wish. This is what we are doing for most of our sites. For example, 
https://sparkplug.eclipse.org/news/

`<div id="news-list-container" class="news-items" data-pagination="true" data-news-count="10" data-publish-target="tangle_ee"></div>`

For events, we recommend linking to the homepage of our Event website: https://events.eclipse.org

**Comment by begonaalvarezd** [comment] 2020-08-29 11:11
Deployed #10. 
Closing issue.

**Closed by begonaalvarezd** 2020-08-29 11:11 UTC
